name: custom_ping
description: A ping service to fix the ping issue on Colombia networks. Where a valid ping donsnt mean the phone will have navigation
version: 0.2.3+1
homepage: https://github.com/oscarshaitan/custom_ping

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.otigreros.custom_ping
        pluginClass: CustomPingPlugin
      ios:
        pluginClass: CustomPingPlugin
      macos:
        pluginClass: CustomPingPlugin
